---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grpca
---
apiVersion: v1
kind: Service
metadata:
  name: grpca
  labels:
    app: grpca
    service: grpca
spec:
  ports:
  - name: grpc
    port: 9000
    targetPort: 9000
    appProtocol: grpc
  selector:
    app: grpca
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpca
      version: v1
  template:
    metadata:
      labels:
        app: grpca
        version: v1
    spec:
      nodeName: ambient-worker
      serviceAccountName: grpca
      containers:
      - image: docker.io/knabben/grpcbin:latest
        imagePullPolicy: Always
        name: grpca
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grpcb
---
apiVersion: v1
kind: Service
metadata:
  name: grpcb
  labels:
    app: grpcb
    service: grpcb
spec:
  ports:
  - name: grpc
    port: 9000
    targetPort: 9000
    appProtocol: grpc
  selector:
    app: grpcb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpcb
      version: v2
  template:
    metadata:
      labels:
        app: grpcb
        version: v2
    spec:
      nodeName: ambient-worker2
      serviceAccountName: grpcb
      containers:
      - image: docker.io/knabben/grpcbin:latest
        imagePullPolicy: Always
        name: grpcb
        ports:
        - containerPort: 9000
