// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.2
// source: bank.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CasinoClient is the client API for Casino service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CasinoClient interface {
	PayIt(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionReply, error)
}

type casinoClient struct {
	cc grpc.ClientConnInterface
}

func NewCasinoClient(cc grpc.ClientConnInterface) CasinoClient {
	return &casinoClient{cc}
}

func (c *casinoClient) PayIt(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionReply, error) {
	out := new(TransactionReply)
	err := c.cc.Invoke(ctx, "/bank.Casino/PayIt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CasinoServer is the server API for Casino service.
// All implementations must embed UnimplementedCasinoServer
// for forward compatibility
type CasinoServer interface {
	PayIt(context.Context, *TransactionRequest) (*TransactionReply, error)
	mustEmbedUnimplementedCasinoServer()
}

// UnimplementedCasinoServer must be embedded to have forward compatible implementations.
type UnimplementedCasinoServer struct {
}

func (UnimplementedCasinoServer) PayIt(context.Context, *TransactionRequest) (*TransactionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayIt not implemented")
}
func (UnimplementedCasinoServer) mustEmbedUnimplementedCasinoServer() {}

// UnsafeCasinoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CasinoServer will
// result in compilation errors.
type UnsafeCasinoServer interface {
	mustEmbedUnimplementedCasinoServer()
}

func RegisterCasinoServer(s grpc.ServiceRegistrar, srv CasinoServer) {
	s.RegisterService(&Casino_ServiceDesc, srv)
}

func _Casino_PayIt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CasinoServer).PayIt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bank.Casino/PayIt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CasinoServer).PayIt(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Casino_ServiceDesc is the grpc.ServiceDesc for Casino service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Casino_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bank.Casino",
	HandlerType: (*CasinoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PayIt",
			Handler:    _Casino_PayIt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bank.proto",
}
